In [2]:
# Contoh Data Cleaning dengan Python
import pandas as pd
import numpy as np
# Membuat dataframe contoh
data = {
'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Eve', np.nan],
'Age': [25, 30, 35, 25, np.nan, 50],
'City': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Miami', 'LosAngeles']
}
df = pd.DataFrame(data)
# Menampilkan data awal
print("Data Awal:")
print(df)
# Menghapus duplikat
df = df.drop_duplicates()
# Menangani missing values dengan mengisi nilai median untuk kolom numerik
df['Age'] = df['Age'].fillna(df['Age'].median())
# Menghapus baris yang mengandung missing values di kolom 'Name'
df = df.dropna(subset=['Name'])
# Menampilkan data setelah cleaning
print("\nData Setelah Cleaning:")
df

Data Awal:
      Name   Age         City
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie  35.0      Chicago
3    Alice  25.0     New York
4      Eve   NaN        Miami
5      NaN  50.0   LosAngeles

Data Setelah Cleaning:


Name   Age         City
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie  35.0      Chicago
4      Eve  32.5        Miami

In [4]:
# Identifikasi Missing Values
import pandas as pd
df = pd.read_csv('data.csv')
print(df.isnull().sum())

Name    1
Age     1
City    0
dtype: int64


In [10]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Age'] = df['Age'].fillna(df['Age'].mode()[0])


In [11]:
# Forward/Backward Fill
df['Age'].fillna(method='ffill', inplace=True) # Forward fill
df['Age'].fillna(method='bfill', inplace=True) # Backward fill

C:\Users\taufiq\AppData\Local\Temp\ipykernel_17836\741149105.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(method='ffill', inplace=True) # Forward fill
C:\Users\taufiq\AppData\Local\Temp\ipykernel_17836\741149105.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Age'].fillna(method='ffill', inplace=True) # Forward fill
C:\Users\taufiq\AppData\Local\Temp\ipykernel_17836\741149105.py:3: FutureWarning: A value is 

In [14]:
# Identifikasi duplikat
print(df.duplicated().sum())
# Menghapus duplikat
df.drop_duplicates(inplace=True)

0


In [17]:
# Langkah 1: Membuat DataFrame
import pandas as pd
import numpy as np
data = {
'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Eve', np.nan],
'Age': [25, 30, 35, 25, np.nan, 50],
'City': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Miami', 'LosAngeles']
}
df = pd.DataFrame(data)
# Langkah 2: Identifikasi Outliers
# Outliers dapat diidentifikasi menggunakan berbagai metode, salah satu yang umumadalah menggunakan Z-score atau IQR (Interquartile Range).
# Di sini, kita akan menggunakan IQR untuk mendeteksi outliers.
# Menghitung IQR
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)
IQR = Q3 - Q1
# Menentukan batas bawah dan atas untuk outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
# Menandai outliers
outliers = df[(df['Age'] < lower_bound) | (df['Age'] > upper_bound)]
print("Outliers:\n", outliers)
# Langkah 3: Menangani Outliers
# # Menghapus outliers
df_no_outliers = df[(df['Age'] >= lower_bound) & (df['Age'] <= upper_bound)]
# Mengganti outliers dengan nilai median
median_age = df['Age'].median()
df['Age'] = np.where((df['Age'] < lower_bound) | (df['Age'] > upper_bound),
median_age, df['Age'])
# Mengisi missing values dengan median
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Name'].fillna('Unknown', inplace=True)


Outliers:
 Empty DataFrame
Columns: [Name, Age, City]
Index: []


C:\Users\taufiq\AppData\Local\Temp\ipykernel_17836\3560784508.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)
C:\Users\taufiq\AppData\Local\Temp\ipykernel_17836\3560784508.py:32: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

F

In [19]:
# Contoh: misalnya, kita memiliki dataset dengan kolom "City" yang berisi datakategorikal:
import pandas as pd
data = {'City': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Miami']}
df = pd.DataFrame(data)
# One-Hot Encoding
df_one_hot = pd.get_dummies(df, columns=['City'])
print(df_one_hot)

   City_Chicago  City_Los Angeles  City_Miami  City_New York
0         False             False       False           True
1         False              True       False          False
2          True             False       False          False
3         False             False       False           True
4         False             False        True          False


In [23]:
import numpy as np
data = {
'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Eve', np.nan],
'Age': [25, 30, 35, 25, np.nan, 50],
'City': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Miami', 'LosAngeles']
}
df = pd.DataFrame(data)
# Menghapus Data Tidak Valid: Jika jumlah data tidak valid kecil dan tidaksignifikan, menghapusnya bisa menjadi solusi yang cepat dan mudah.
df = df.dropna(subset=['Age', 'Name']) # Menghapus baris dengan nilai 'Age' atau'Name' yang tidak valid
# Mengganti dengan Nilai Lain:
# Mengisi dengan Rata-rata/Median: Mengisi nilai yang hilang atau tidak validdengan rata-rata atau median.
df['Age'] = df['Age'].fillna(df['Age'].median())
# Mengisi dengan Nilai Default: Mengisi dengan nilai default yang logis atausesuai konteks.
df['Name'] = df['Name'].fillna('Unknown')
# Transformasi Data: Mengubah data tidak valid menjadi format yang sesuai.
df['Age'] = pd.to_numeric(df['Age'], errors='coerce') # Mengubah nilai 'Age'yang tidak valid menjadi NaN
# Pembersihan dengan Logika Bisnis: Menggunakan aturan bisnis untuk memperbaikidata. Misalnya, jika usia tidak masuk akal (misalnya lebih dari 120 tahun), makaubah atau hapus.

df = df[(df['Age'] >= 0) & (df['Age'] <= 120)]

In [24]:
import pandas as pd
import numpy as np
data = {
'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Eve', np.nan],
'Age': [25, 30, 35, 25, np.nan, 150], # 150 dianggap sebagai nilai tidavalid
'City': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Miami', 'LosAngeles']
}
df = pd.DataFrame(data)
# Identifikasi nilai tidak valid
print("Data Awal:")
print(df)
# Mengubah nilai 'Age' yang tidak valid menjadi NaN
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
# Mengisi nilai 'Age' yang hilang atau tidak valid dengan median
df['Age'] = df['Age'].fillna(df['Age'].median())
# Mengisi nilai 'Name' yang hilang dengan 'Unknown'
df['Name'] = df['Name'].fillna('Unknown')
print("\nData Setelah Menangani Nilai Tidak Valid:")
print(df)

Data Awal:
      Name    Age         City
0    Alice   25.0     New York
1      Bob   30.0  Los Angeles
2  Charlie   35.0      Chicago
3    Alice   25.0     New York
4      Eve    NaN        Miami
5      NaN  150.0   LosAngeles

Data Setelah Menangani Nilai Tidak Valid:
      Name    Age         City
0    Alice   25.0     New York
1      Bob   30.0  Los Angeles
2  Charlie   35.0      Chicago
3    Alice   25.0     New York
4      Eve   30.0        Miami
5  Unknown  150.0   LosAngeles


In [25]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression
import numpy as np
# Contoh dataset
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]])
y = np.array([2, 3, 4, 5, 6])
# Model
model = LinearRegression()
# K-Fold Cross-Validation
kf = KFold(n_splits=5)
scores = cross_val_score(model, X, y, cv=kf)
print("K-Fold Cross-Validation Scores:", scores)
print("Mean Score:", np.mean(scores))

K-Fold Cross-Validation Scores: [nan nan nan nan nan]
Mean Score: nan


C:\Users\taufiq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_regression.py:1211: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\taufiq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_regression.py:1211: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\taufiq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_regression.py:1211: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\taufiq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p

In [26]:
# Implementasi K-Fold Cross-Validation di Python
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
# Load dataset
iris = load_iris()
X = iris.data
y = iris.target
# Model
model = LogisticRegression(max_iter=1000)
# K-Fold Cross-Validation
kf = KFold(n_splits=5, shuffle=True, random_state=42) # Misalnya, menggunakan 5folds dengan shuffle dan seed random 42
scores = cross_val_score(model, X, y, cv=kf, scoring='accuracy')
print("K-Fold Cross-Validation Scores:", scores)
print("Mean Score:", scores.mean())

K-Fold Cross-Validation Scores: [1.         1.         0.93333333 0.96666667 0.96666667]
Mean Score: 0.9733333333333334


In [28]:
import numpy as np
# Data
data = np.array([10, 15, 8, 12, 14, 20, 18, 16, 11, 13])

# Bootstrap sampling
n_samples = 1000
bootstrap_means = np.zeros(n_samples)

for i in range(n_samples):
    bootstrap_sample = np.random.choice(data, size=len(data), replace=True)
    bootstrap_means[i] = np.mean(bootstrap_sample)
    
# Confidence interval (95%)
ci_lower = np.percentile(bootstrap_means, 2.5)
ci_upper = np.percentile(bootstrap_means, 97.5)

print("Mean:", np.mean(data))
print("95% Confidence Interval:", ci_lower, "-", ci_upper)

Mean: 13.7
95% Confidence Interval: 11.6 - 15.9


In [33]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Bagi dataset menjadi data pelatihan dan data pengujian (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inisialisasi dan latih model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Prediksi dengan data pengujian
y_pred = model.predict(X_test)

# Evaluasi kinerja model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Tampilkan hasil
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [2]:
# Impor library yang diperlukan
import nltk
from nltk.corpus import movie_reviews
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix, classification_report

# Unduh dataset sentimen ulasan film dari NLTK
nltk.download('movie_reviews')

# Ambil ulasan dan label dari dataset
documents = [(list(movie_reviews.words(fileid)), category)
             for category in movie_reviews.categories()
             for fileid in movie_reviews.fileids(category)]

# Pisahkan teks ulasan dan label
texts = [' '.join(document) for document, category in documents]
labels = [category for document, category in documents]

# Ubah teks menjadi vektor fitur TF-IDF
vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(texts)

# Bagi dataset menjadi data pelatihan dan data pengujian
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=42)

# Inisialisasi dan latih model klasifikasi (Linear SVM)
classifier = LinearSVC()
classifier.fit(X_train, y_train)

# Prediksi kelas pada data pengujian
y_pred = classifier.predict(X_test)

# Evaluasi model menggunakan confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Evaluasi model menggunakan classification report
report = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(report)


[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\taufiq\AppData\Roaming\nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!


Confusion Matrix:
[[170  29]
 [ 37 164]]

Classification Report:
              precision    recall  f1-score   support

         neg       0.82      0.85      0.84       199
         pos       0.85      0.82      0.83       201

    accuracy                           0.83       400
   macro avg       0.84      0.84      0.83       400
weighted avg       0.84      0.83      0.83       400



In [13]:
# Dropping Missing Values
df.dropna(subset=['Age'], inplace=True)